dependencies={
    layers:[
        {
            copyrightFile:"CUSTOM_LAYER_NOTICE.txt",
            name:"lwg.js",
            dependencies:[
                "dijit.form.Button",
                "dijit.form.Form",
                "dijit.form.ValidationTextBox"
            ]
        }
    ],
    prefixes:[
        ["dijit","../dijit"],
        ["foo","../foo","CUSTOM_FILE_NOTICE.txt"]
    ]
}